# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainProjectWidget.ui'
#
# Created: Sat Nov 16 09:10:50 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainProjectWidget(object):
    def setupUi(self, MainProjectWidget):
        MainProjectWidget.setObjectName(_fromUtf8("MainProjectWidget"))
        MainProjectWidget.resize(999, 664)
        self.btn_choose_video = QtGui.QPushButton(MainProjectWidget)
        self.btn_choose_video.setGeometry(QtCore.QRect(520, 10, 161, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/folder_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_choose_video.setIcon(icon)
        self.btn_choose_video.setIconSize(QtCore.QSize(40, 40))
        self.btn_choose_video.setObjectName(_fromUtf8("btn_choose_video"))
        self.txt_main_video = QtGui.QPlainTextEdit(MainProjectWidget)
        self.txt_main_video.setGeometry(QtCore.QRect(10, 10, 501, 41))
        self.txt_main_video.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_main_video.setObjectName(_fromUtf8("txt_main_video"))
        self.seek_slider = phonon.Phonon.SeekSlider(MainProjectWidget)
        self.seek_slider.setGeometry(QtCore.QRect(100, 440, 451, 41))
        self.seek_slider.setObjectName(_fromUtf8("seek_slider"))
        self.volume_slider = phonon.Phonon.VolumeSlider(MainProjectWidget)
        self.volume_slider.setGeometry(QtCore.QRect(560, 440, 114, 41))
        self.volume_slider.setObjectName(_fromUtf8("volume_slider"))
        self.time_edit = QtGui.QTimeEdit(MainProjectWidget)
        self.time_edit.setGeometry(QtCore.QRect(10, 620, 118, 27))
        self.time_edit.setObjectName(_fromUtf8("time_edit"))
        self.btn_pause = QtGui.QPushButton(MainProjectWidget)
        self.btn_pause.setGeometry(QtCore.QRect(10, 440, 41, 41))
        self.btn_pause.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/button_blue_pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon1)
        self.btn_pause.setIconSize(QtCore.QSize(40, 40))
        self.btn_pause.setObjectName(_fromUtf8("btn_pause"))
        self.btn_stop = QtGui.QPushButton(MainProjectWidget)
        self.btn_stop.setGeometry(QtCore.QRect(50, 440, 41, 41))
        self.btn_stop.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/button_blue_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon2)
        self.btn_stop.setIconSize(QtCore.QSize(40, 40))
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.btn_play = QtGui.QPushButton(MainProjectWidget)
        self.btn_play.setGeometry(QtCore.QRect(10, 440, 41, 41))
        self.btn_play.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/button_blue_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon3)
        self.btn_play.setIconSize(QtCore.QSize(40, 40))
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.btn_add_annotation = QtGui.QPushButton(MainProjectWidget)
        self.btn_add_annotation.setGeometry(QtCore.QRect(130, 610, 191, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/comment_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_annotation.setIcon(icon4)
        self.btn_add_annotation.setIconSize(QtCore.QSize(40, 40))
        self.btn_add_annotation.setObjectName(_fromUtf8("btn_add_annotation"))
        self.frame_notes = QtGui.QFrame(MainProjectWidget)
        self.frame_notes.setGeometry(QtCore.QRect(690, 10, 301, 641))
        self.frame_notes.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_notes.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_notes.setObjectName(_fromUtf8("frame_notes"))
        self.label = QtGui.QLabel(self.frame_notes)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.list_notes = QtGui.QListWidget(self.frame_notes)
        self.list_notes.setGeometry(QtCore.QRect(10, 30, 281, 551))
        self.list_notes.setObjectName(_fromUtf8("list_notes"))
        self.btn_edit = QtGui.QPushButton(self.frame_notes)
        self.btn_edit.setGeometry(QtCore.QRect(10, 590, 131, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/comment_edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon5)
        self.btn_edit.setIconSize(QtCore.QSize(40, 40))
        self.btn_edit.setObjectName(_fromUtf8("btn_edit"))
        self.btn_delete = QtGui.QPushButton(self.frame_notes)
        self.btn_delete.setGeometry(QtCore.QRect(160, 590, 131, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/comment_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon6)
        self.btn_delete.setIconSize(QtCore.QSize(40, 40))
        self.btn_delete.setObjectName(_fromUtf8("btn_delete"))
        self.btn_generate_ncl = QtGui.QPushButton(MainProjectWidget)
        self.btn_generate_ncl.setGeometry(QtCore.QRect(380, 610, 151, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/notepad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_generate_ncl.setIcon(icon7)
        self.btn_generate_ncl.setIconSize(QtCore.QSize(40, 40))
        self.btn_generate_ncl.setObjectName(_fromUtf8("btn_generate_ncl"))
        self.btn_save_project = QtGui.QPushButton(MainProjectWidget)
        self.btn_save_project.setGeometry(QtCore.QRect(530, 610, 151, 41))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/i/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_project.setIcon(icon8)
        self.btn_save_project.setIconSize(QtCore.QSize(40, 40))
        self.btn_save_project.setObjectName(_fromUtf8("btn_save_project"))
        self.video_player = phonon.Phonon.VideoPlayer(MainProjectWidget)
        self.video_player.setGeometry(QtCore.QRect(10, 60, 671, 371))
        self.video_player.setObjectName(_fromUtf8("video_player"))
        self.txt_description = QtGui.QTextEdit(MainProjectWidget)
        self.txt_description.setGeometry(QtCore.QRect(10, 490, 671, 101))
        self.txt_description.setObjectName(_fromUtf8("txt_description"))

        self.retranslateUi(MainProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(MainProjectWidget)

    def retranslateUi(self, MainProjectWidget):
        MainProjectWidget.setWindowTitle(QtGui.QApplication.translate("MainProjectWidget", "Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_video.setText(QtGui.QApplication.translate("MainProjectWidget", "Escolha o Vídeo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_annotation.setText(QtGui.QApplication.translate("MainProjectWidget", "Adicionar Anotação", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainProjectWidget", "Anotações:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_edit.setText(QtGui.QApplication.translate("MainProjectWidget", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete.setText(QtGui.QApplication.translate("MainProjectWidget", "Excluir", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_generate_ncl.setText(QtGui.QApplication.translate("MainProjectWidget", "Gerar NCL", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_project.setText(QtGui.QApplication.translate("MainProjectWidget", "Salvar Projeto", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
import icons_rc
